version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  broker:
    image: confluentinc/cp-kafka:7.6.0
    depends_on: [zookeeper]
    ports: ["9092:9092"]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin

  producer:
    build: .
    command: python rss_producer.py
    depends_on: [broker]
    environment:
      KAFKA_BROKER: broker:9092
      KAFKA_TOPIC: financial_headlines_pl

  consumer:
    build: .
    command: python python_consumer.py
    depends_on: [broker, mongo]
    environment:
      KAFKA_BROKER: broker:9092
      KAFKA_TOPIC: financial_headlines_pl
      MONGO_USER: root
      MONGO_PASSWORD: admin
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_AUTH_SOURCE: admin
